# Generated by Django 4.2.4 on 2023-08-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_title_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='hello world', max_length=100),
            preserve_default=False,
        ),
    ]
